apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-ecommerce
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sohail-24/django_ecommerce_infra.git
    targetRevision: main
    path: charts/django-ecommerce

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
