name: 🚀 EKS ZERO-MANUAL DEPLOY PIPELINE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 150

    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: aws_eks-eks
      NODEGROUP_NAME: aws_eks-eks-nodes

    steps:

    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - uses: azure/setup-kubectl@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Wait Cluster
      run: aws eks wait cluster-active --name $CLUSTER_NAME

    - name: Configure kubeconfig
      run: aws eks update-kubeconfig --name $CLUSTER_NAME

    - name: Wait Nodegroup
      run: |
        aws eks wait nodegroup-active \
          --cluster-name $CLUSTER_NAME \
          --nodegroup-name $NODEGROUP_NAME

    - name: Wait Nodes
      run: kubectl wait --for=condition=Ready nodes --all --timeout=600s

    - name: Wait CSI
      run: |
        kubectl wait --for=condition=Ready pods \
          -l app.kubernetes.io/name=aws-ebs-csi-driver \
          -n kube-system --timeout=600s

    - name: Wait ArgoCD
      run: |
        kubectl wait --for=condition=Ready pods \
          -n argocd \
          -l app.kubernetes.io/part-of=argocd \
          --timeout=600s

    - name: Apply Argo App
      run: kubectl apply -f argocd/app.yaml

    - name: Wait App
      run: |
        kubectl wait --for=condition=Ready pod -l app=django -n ecommerce --timeout=600s
        kubectl wait --for=condition=Ready pod -l app=postgres -n ecommerce --timeout=600s
        kubectl wait --for=condition=Ready pod -l app=redis -n ecommerce --timeout=600s

    - name: Wait LB
      run: |
        for i in {1..40}; do
          LB=$(kubectl get svc django -n ecommerce -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          [ ! -z "$LB" ] && echo "🌍 $LB" && exit 0
          sleep 15
        done
        exit 1
